columns:
- Close
- High
- Low
- Open
- Volume
- Return
- RollingVolatility
- VolumeMA20
- NormalizedVolume
- TrueRange
- ATR
- Pivot
- Resistance1
- Support1
- Resistance2
- Support2
- MA50
- PriceDev_MA50
- PriceDev_Pivot
- NASDAQ_Close
- NASDAQ_Return
- Corr_SP500_NASDAQ_20
- RelStrength_SP500_NASDAQ
created_at: '2025-10-24T00:14:21.905267'
feature_count: 23
long_k: 0.6
short_k: 0.6
